### ISSUE TITLE
Improve Avatar editor performance

### ISSUE THREAD

**Issue by marcosnc** [decentraland/explorer#1001]
It takes 2-3 seconds to change a wearable. Should be milliseconds
We need to identify the cause that makes it taking so long.
If it's the time required to save the profile, maybe we could perform the action asynchronously, and if it fails allow the user to retry it.

**Comment by BrianAmadori** [comment]
This was already improved as part of our latest performance effort. Let's re-open this if we find its already a concern. Take into account that the wearables have to be downloaded the first time they are used.
