### ISSUE TITLE
Avoid missing patches when entering the map

### ISSUE THREAD

**Issue by marcosnc** [decentraland/explorer#1005]
There are some "black square" that get shown when the map is opened the first time.

We need to confirm if the images that build the background in the minimap are downloaded beforehand or if they are downloaded when the user opens the map for the first time.

Ideally, we should create a non-blocking queue to download this content and other content (like the error screens, etc), so all the content is downloaded (and cached) previous to it's required but without blocking other processes.

**Comment by BrianAmadori** [comment]
This is not a bug, is a feature request. Just removed the label to reflect that.
