### ISSUE TITLE
GLTF triangle count 3X higher than it should

### ISSUE THREAD

**Issue by nearnshaw** [decentraland/explorer#111]
Try this item:

[https://app.zenhub.com/files/220994476/3e9e044c-b890-460c-bb94-72b88dc3c1f4/download](https://app.zenhub.com/files/220994476/3e9e044c-b890-460c-bb94-72b88dc3c1f4/download)

In Blender, it says it has 492 triangles (let's consider that the more accurate measurement)

If I use it in a scene, the panel says 1476  (x3)

If I import it to the Builder, says 1572 (that counts the ground that I can't remove)

The same happens w another gltf someone from the community passed me, that is too big to upload here.  Ask me for it if you need to see it

**Comment by eordano** [comment]
@nearnshaw is this open still?
