### ISSUE TITLE
Too many green blockers when trying to explore the world

### ISSUE THREAD

**Issue by BrianAmadori** [decentraland/explorer#1201]
Lately, with incresing frequency we have been observing that scenes fail to load and get into a perpetual pending state when walking around the world.

I think is observed more than often at `artemis-pink` and its related to scene.json slow/delayed requests in the scene worker.

![image](https://user-images.githubusercontent.com/6875814/90910576-edff4b80-e3ad-11ea-8896-46b4cc00fd8a.png)

**Comment by marcosnc** [comment]
I think we should divide the cases when the green blockers never disappear from the cases when they just take too long.
The former cases may be caused by halted scenes.
The later cases may be caused by the thtottling we added in the download process to avoid hiccups (what do you think @sandrade-dcl ?).

**Comment by sandrade-dcl** [comment]
@marcosnc related to the cases when the green blockers take too long, I'm not sure that it is being provoked by the throttling we added on our last performance changes. I have the feeling that it could be provoked by something in the AB loading in scene process (I mean after the AB has been already downloaded and internally loaded by Unity), and not by requesting the ABs. Anyway, to be sure, we could try to do some tests changing the configuration params that I put on the `AssetBundlesLoader` class related to the throttling. These parameters are the next:

- `MAX_LOAD_BUDGET_TIME`: Each time we reach this time, the system will await for a number of frames to continue loading assets.
- `SKIPPED_FRAMES_AFTER_BUDGET_TIME_IS_REACHED_FOR_NEARBY_ASSETS`: Number of frames that we will await when we reach the `MAX_LOAD_BUDGET_TIME` for nearby assets.
- `SKIPPED_FRAMES_AFTER_BUDGET_TIME_IS_REACHED_FOR_DISTANT_ASSETS`: Number of frames that we will await when we reach the `MAX_LOAD_BUDGET_TIME` for distant assets.
- `MAX_SQR_DISTANCE_FOR_QUICK_LOADING`: This is the distance that will be used to determinate if an asset is near or distant.
- `TIME_BETWEEN_REPRIORITIZATIONS`: Minimum time that will pass between each assets reprioritization (this reprioritization is the process we do for move some assets from the distant list to the nearby one while we are moving along the world).

Trying to change these values and do several tests in the world could be a good starting point to confirm if the throttling is the origin of the problem or not.

**Comment by BrianAmadori** [comment]
This issue is mostly duplicated, it should be covered by:
https://github.com/decentraland/explorer/issues/1190
https://github.com/decentraland/explorer/issues/1286

I'm closing it until we fix those two. If the green blockers issue is still present at that point, we can open another issue with more details.
