### ISSUE TITLE
Asset bundles fail to be converted in several areas

### ISSUE THREAD

**Issue by BrianAmadori** [decentraland/explorer#1207]
Some areas are never converted to asset bundles, leading to poor loading performance.

Observed in Tomb Chaser and parcels surrounding Momus Park.

**Comment by marcosnc** [comment]
I calculated a new graphical representation of the current asset bundle status.
The color code is as follows:
* White: no scenes
* Green: scenes with all their Asset Bundles calculated OK
* Black to Red: Scenes with missing Asset Bundles (Black few, Red many)

![image.png](https://images.zenhubusercontent.com/5dc174a011dec50001486869/7a41e8cc-d684-4762-8e13-81361283fdac)
