### ISSUE TITLE
Scene performance drops after being open 20-30 minutes

### ISSUE THREAD

**Issue by nearnshaw** [decentraland/explorer#1340]
Baus (Miles) reported this issue. He created a simple scene and it works fine if loaded freshly. But if he keeps the scene open for an hour and then tries to interact with it, the update function is very laggy. Even though the reported FPS are still good.

Here's his description:

Did some tests and there's definitely some weird stuff going on with the DCL engine's update() logic that's responsible for the stuttering issues that worsen over time in blackjack and poker

```ts
import utils from "../node_modules/decentraland-ecs-utils/index";
let box = new Entity();
box.addComponent(new BoxShape());
box.addComponent(
  new Transform({
    position: new Vector3(8, 0, 8),
  })
);
box.addComponent(
  new OnPointerDown((e) => {
    spawnCubes();
  })
);
engine.addEntity(box);
function spawnCubes() {
  let root = new Entity();
  engine.addEntity(root);
  const blue = new Material();
  blue.albedoColor = Color3.Blue();
  for (let i = 0; i < 5; i++) {
    let el = new Entity();
    el.addComponent(new BoxShape());
    el.addComponent(blue);
    let startPos = new Vector3(6, 0.3 + i * 0.5, 6);
    el.addComponent(
      new Transform({
        position: startPos,
        scale: new Vector3(0.3, 0.3, 0.3),
      })
    );
    el.setParent(root);
    el.addComponent(
      new utils.Delay(500, () => {
        el.addComponent(
          new utils.MoveTransformComponent(startPos, startPos.add(new Vector3(2, 0, 0)), 1.5, () =>
            el.addComponent(
              new utils.Delay(500, () => {
                engine.removeEntity(root);
              })
            )
          )
        );
      })
    );
  }
}
```

So I used this pretty basic code snipped that triggered an animation when the white button was pressed, this is using utils.MoveTransformComponent in DCL's utils library

Here's a vid of an instance where I let it sit for around an hour and triggered it and the animations are insanely laggy even though the client maintains >140 fps, then you can see right afterwards when I load a fresh instance it works properly (edited)

https://decentralandteam.slack.com/files/UNGGR372Q/F01BSU3HA2U/2020-09-20_13-50-10.mp4

This is with my desktop which is pretty well-specced so I have a feeling this could be happening even quicker on laptops (like ~20 mins like the blackjack feedback we got)

**Comment by pravusjif** [comment]
This issue is solved in 2 fronts:

Kernel's `engine.getComponentGroup()` optimization in the following PR:
https://github.com/decentraland/explorer/pull/1551

And `decentraland-ecs-utils` TransformSystem memory leak fix in the following PR:
https://github.com/decentraland/decentraland-ecs-utils/pull/16
