### ISSUE TITLE
The shiny gold look on this mask material etc was lost in commit 7c3b323

### ISSUE THREAD

**Issue by cfravel** [decentraland/explorer#1346]
There was a materials change in 7c3b323 that caused the mask in the Grand Theater scene in the Conference center to go from shiny gold to a dull bronze look, and the artists' signature text to disappear entirely.

6.4.9-20200526174530.commit-bf81ee7 was good
'6.4.9-20200526211756.commit-7c3b323 lost the gold look and signature.

Code snippet:
structure.addComponent(new GLTFShape("models/grand-theater-v4/cleanTheatre13.glb"))

Screenshot images before and after are attached.

You can see this if you face north at 29,113

Seen on Chrome, Windows, no VR headset

Looks good like this up through 6.4.9-20200526174530.commit-bf81ee7
![GrandTheater-CLI_3 4 3_ECS_6 4 8_GBLv4](https://user-images.githubusercontent.com/21015643/93820382-b55bc780-fc22-11ea-8df0-0609b3f83df8.png)

Builds from on or after this lose the material rendering:  6.4.9-20200526211756.commit-7c3b323
![GrandTheater-CLI_3 4 3_ECS_6 4 9_GBLv4](https://user-images.githubusercontent.com/21015643/93820391-b856b800-fc22-11ea-8c26-ca034bb8348c.png)

**Comment by AjimenezDCL** [comment]
We discovered the issue has nothing to do with materials/shaders but with the new reflection texture.
