### ISSUE TITLE
Scenes audio is playing even if the character is outside the scene

### ISSUE THREAD

**Issue by pravusjif** [decentraland/explorer#1352]
This was observed particularly when using video streaming

**Comment by nchamo** [comment]
Hey @pravusjif !

Would this also fix https://github.com/decentraland/explorer/issues/1276 ?

**Comment by pravusjif** [comment]
> Hey @pravusjif !
> 
> Would this also fix #1276 ?

Yes this should solve that issue as long as the character gets outside the scene
