### ISSUE TITLE
Child entities with a trigger area go into full epilepsy mode

### ISSUE THREAD

**Issue by nearnshaw** [decentraland/explorer#1358]
I noticed this happening in entities that are children of another entity AND that have the TriggerComponent from the Utils library.
I'm not sure how long this has been happening, but it's currently happening both in @latest and in @next

Here's a minimal example where that happens:
[https://app.zenhub.com/files/220994476/6490dc2e-faa6-4dfe-b550-bac4e856d0b1/download](https://app.zenhub.com/files/220994476/6490dc2e-faa6-4dfe-b550-bac4e856d0b1/download)

```ts
import utils from '../node_modules/decentraland-ecs-utils/index'

let scene = new Entity()
scene.addComponent(
  new Transform({
    position: new Vector3(0, 0, 0),
    rotation: Quaternion.Euler(0, 90, 0),
  })
)
engine.addEntity(scene)

export let building = new Entity()
building.addComponent(
  new Transform({
    position: new Vector3(16, 0, 16),
  })
)
building.addComponent(new GLTFShape('models/FoxAsian.glb'))
building.setParent(scene)

let triggerBox = new utils.TriggerBoxShape(Vector3.One(), Vector3.Zero())

building.addComponent(
  new utils.TriggerComponent(
    triggerBox, //shape
    0, //layer
    0, //triggeredByLayer
    null, //onTriggerEnter
    null, //onTriggerExit
    () => {
      log('inside')
    }
  )
)
```

Like this, the 3d model jumps every frame between 4 different locations in the scene.

If I set the position of the model directly, without the parent, it gets fixed.
If I remove the TriggerComponent, it gets fixed.
If I remove the last argument of the TriggerComponent, so that it has a trigger area but doesn't have a triggered function, it gets fixed.

**Comment by BrianAmadori** [comment]
@pbosio maybe you can get a better insight into this one, that trigger component is part of your utils library right?

**Comment by pbosio** [comment]
> @pbosio maybe you can get a better insight into this one, that trigger component is part of your utils library right?

It's not **my** utils library... it's **our** utils library 😒 the world's utils library!
I will take a look, as far as I remember the triggers never moved or rotate anything... but... maybe those old functions for getting the global position or rotation of an entity are doing something crazy here? 🤔

**Comment by pbosio** [comment]
Yeap.. As I suspected there was an issue with the function to calculate the position of the child entity in world space. (it was using a reference instead of a copy)
I have pushed a fix to the repo and should be available to update the npm package in your scene @nearnshaw

**Comment by nearnshaw** [comment]
Nice!!
Thanks @pbosio ❤️
