### ISSUE TITLE
Technical document for multi camera input modes support

### ISSUE THREAD

**Issue by BrianAmadori** [decentraland/explorer#136]
Right now our architecture doesn't support multiple camera modes out of the box, leading to implementations that generate a lot of technical debt. 

We need a document to define a refactor that would improve the codebase quality and allow iteration that doesn't generate residual code.

**Comment by eordano** [comment]
This is done, right?

**Comment by AjimenezDCL** [comment]
It's almost done, @BrianAmadori wanted to add some little details. I think we can close it and work off the board.

**Comment by AjimenezDCL** [comment]
https://docs.google.com/document/d/1jhH-4chFo0k_dtBDZnHbAmPk6J9N1ZwtJV_iWcI8LDo/edit?ts=5ddc743b
