### ISSUE TITLE
when teleporting avatars using the SDK, other users see the avatar lerping its position

### ISSUE THREAD

**Issue by nchamo** [decentraland/explorer#1374]
When "teleporting" or moving the player with the new `movePlayerTo` SDK action causes the `fly` animation to be executed. One of our users said:
```
Regarding moving the player (new service movePlayerTo), I see the avatar being animated (small jump) each time the service is called. It makes sense in some cases, but IMHO it would prevent from moving the player smoothly on a path, for example.
Is there a way to deactivate the jump, by any chance ?
```

**Comment by LeonChain** [comment]
I would like to help with issues.
Is there anyone I can chat with for this?

**Comment by marcosnc** [comment]
Hi @elitedev1314520 I would love to help you with this! Please contact me at marcos@decentraland.org

**Comment by elitedev1314520** [comment]
thanks @nchamo
