### ISSUE TITLE
On every HUD, esc key should close the window.

### ISSUE THREAD

**Issue by RominaMarchetti** [decentraland/explorer#1379]
This key behavior is missing into the following HUDS

- [x] Explore 

- [x] Profile  

- [x] Settings 

- [x] Help

- [ ] Avatar editor

**Comment by AjimenezDCL** [comment]
Weird thing, avatar editor closes with ESC for me. Can you double check it's still happening @RominaMarchetti ?

The rest are indeed not being closed by the key.
