### ISSUE TITLE
Billboards facing the avatar instead of camera on 3rd person view

### ISSUE THREAD

**Issue by cfravel** [decentraland/explorer#1382]
If you are looking at a billboard in firstperson view, it looks right 
If you use "V" to shift to 3rd person view, and move the camera around to the side, you see that it is a cube that is still facing the avatar position, not facing the camera position..

You can see first and 3rd person views of the Info panel billboard in the Lotus Temple at 
https://play.decentraland.org/?position=12,107

First person view:
![BillboardFirstPerson](https://user-images.githubusercontent.com/21015643/94875720-3c771f80-041b-11eb-807c-a8b7a1afeb2c.png)

Third person view:
![BillboardThirdPerson](https://user-images.githubusercontent.com/21015643/94875743-46008780-041b-11eb-9f11-01475b976e8d.png)

**Comment by pravusjif** [comment]
Maybe the billboard nullref reported at #1441 could also be tackled in this PR
