### ISSUE TITLE
Sometimes teleport image and loading images are displayed at the same time.

### ISSUE THREAD

**Issue by marcosnc** [decentraland/explorer#1384]
![image.png](https://images.zenhubusercontent.com/5dc174a011dec50001486869/2b3825d8-6179-4d88-adf7-12530431a71b)

**Comment by caminoezequiel** [comment]
@marcosnc it's fixed in `master`

**Comment by caminoezequiel** [comment]
Can I close the ticket? do we need to link it in the next release?

**Comment by caminoezequiel** [comment]
fixed on this release #1672
