### ISSUE TITLE
TextShape opacity property doesn't work

### ISSUE THREAD

**Issue by nearnshaw** [decentraland/explorer#1392]
The TextShape component has an "opacity" property that should let you make a text semi-transparent. However, if you change that value nothing happens, and there is no other way to make a text semi-transparent.

The following code produces a text that is still 100% opaque
```ts
  const message = new Entity();
  message.addComponent(new TextShape("Test");
  message.addComponent(
    new Transform({ position: new Vector3(8, 1, 8) })
  );
  message.getComponent(TextShape).opacity = 0.5;
engine.addEntity(message)
```

**Comment by AjimenezDCL** [comment]
This will be fixed in #827
