### ISSUE TITLE
GLTF->AB: Make converter work with all poi scenes

### ISSUE THREAD

**Issue by eordano** [decentraland/explorer#14]
Test plan:

1. Go to https://poi.nft.party and enter each scene.
2. Using the current branch, open the same scenes
3. Verify that all assets are loaded correctly on both versions

- [x] Museum District (13, 75) (4/130 assets missing)
- [x] The Battleground (82, 41)
- [x] Sugar Club (-1, -35) (2/109 assets missing)
- [x] The Farm (-3, -33) (36/229 assets missing)
- [x] Enchanneled Wood (-34, -37) (1/187 missing)
- [x] Halloween Scene (66, 6)
- [x] Unique Place (28, -118)
- [x] Medieval Plaza (-63, -65)
- [x] Forest Plaza (-9, 73)
- [x] Koko Jones (-39, 58)
- [x] Genesis Plaza (0, 0)
- [x] Crypto Valley Convention Center (68, 15)
- [x] Maze Race (115, -8)
- [x] ChainBreakers Museum (6, 31)
- [x] Pete PlanetVr's House (-110, -53)

Tested with https://assetbundle.nft.party/

**Comment by BrianAmadori** [comment]
As far as I checked using https://assetbundle.nft.party/ missing assets are just textures that are used without any GLTF model. Those assets aren't migrated to AB by design. So as far as this goes this issue has been completed.
