### ISSUE TITLE
Sometimes the email prompt cannot be closed

### ISSUE THREAD

**Issue by pravusjif** [decentraland/explorer#1418]
Reported by Agus F. (there's a 121mb [video](https://decentralandteam.slack.com/files/US3P78GUV/F01CCDJB490/vid_20201010_164814.mp4) on Slack although it just shows the behaviour happening)

More details by @eordano : 

Reported on [Tominoya](https://play.decentraland.org/?position=-75%2C77)

Also reportedly happening in other scenes (maybe related to scene UIs? Tominoya is pretty heavy on them)

![image (1)](https://user-images.githubusercontent.com/42750/96003759-df2b9700-0e3a-11eb-9c08-412ed67b4146.png)

**Comment by BrianAmadori** [comment]
@marcosnc said:
>lo estuve revisando con Fede, no es un tema del email dialog, sino que no le respondía ningún click del mouse. Tal vez es algo similar a cuando perdíamos los eventos de esc y no podíamos deslockear el mouse.

**Comment by pablitar** [comment]
This issue will probably be fixed by PR #1473.
