### ISSUE TITLE
preview mode: frequent crash upon reload

### ISSUE THREAD

**Issue by menduz** [decentraland/explorer#1422]
![Screen Shot 2020-10-13 at 10 27 05](https://user-images.githubusercontent.com/260114/95866728-a7d7c000-0d3e-11eb-8e6b-6eb8356ca1fa.png)
In the default scene, after "hot-reloading" with the ECS version `6.6.1-20201009223644.commit-48606a5` unity gets broken 2 every 3 times. I get the following errors:

<img width="1440" alt="Screen Shot 2020-10-12 at 19 19 51" src="https://user-images.githubusercontent.com/260114/95865650-4b27d580-0d3d-11eb-90cd-1a8d8be27901.png">

![Screen Shot 2020-10-13 at 10 14 23](https://user-images.githubusercontent.com/260114/95865681-53801080-0d3d-11eb-8c54-046a0b39ac14.png)

## With a F5

![Screen Shot 2020-10-13 at 10 21 16](https://user-images.githubusercontent.com/260114/95866166-f3d63500-0d3d-11eb-9940-30c54f844737.png)

![Screen Shot 2020-10-13 at 10 22 40](https://user-images.githubusercontent.com/260114/95866219-081a3200-0d3e-11eb-8e04-c67d82feccc2.png)

## It seems to fail loading some resources:

![Screen Shot 2020-10-13 at 10 25 50](https://user-images.githubusercontent.com/260114/95866585-78c14e80-0d3e-11eb-9564-13e1660893ff.png)

```bash
# both respond 404
http://127.0.0.1:8000/lambdas/images/QmZbyGxDnZ4PaMVX7kpA2NuGTrmnpwTJ8heKKTSCk4GRJL/256 
http://127.0.0.1:8000/lambdas/images/QmZbyGxDnZ4PaMVX7kpA2NuGTrmnpwTJ8heKKTSCk4GRJL/128
```

I don't attach any code since it fails with the default code for a blank scene.

# Update

It works _every_ time if I click on the page before unity loads. It enables the audio context and doesn't fail. The 404 seems to not affect this specific error. @pablitar 

# Update 2

It keeps failing at random places.

![Screen Shot 2020-10-13 at 10 58 23](https://user-images.githubusercontent.com/260114/95870571-056e0b80-0d43-11eb-8797-b329abe531f1.png)

**Comment by pablitar** [comment]
I've seen this issue (the abnormal situation in the game loop one) pop up from time to time not only on preview, but also running the explorer locally. But it was quite infrequent (Maybe once or twice last week).

Looks like some kind of race condition. But I'm not sure where to look honestly.

**Comment by BrianAmadori** [comment]
This is often the byproduct of another error on wasm side (i.e. a `NullReferenceException`). We should try to trace this one using WSS on Unity and see what's going on.

**Comment by menduz** [comment]
https://github.com/decentraland-scenes/bowling-cannon here it is the sources I used in case anyone wants to test it. Is there a way to run WSS on preview scenes?

**Comment by menduz** [comment]
I couldn't reproduce it anymore, neither in the browser nor unity editor.

**Comment by pravusjif** [comment]
* Tried with an existent dcl preview scene **with and without unity editor**, using **decentraland-ecs@next** and couldn't reproduce the issue
* Tried with a newly created dcl scene, with both **decentraland-ecs@next** and **decentraland-ecs@lates**t and couldn't reproduce the issue

In both tests tried **browser refreshing** and also **hot-reloading**.

**Comment by nchamo** [comment]
Just as an FYI, this has come and gone before
https://github.com/decentraland/explorer/issues/1155

**Comment by BrianAmadori** [comment]
This was a chrome issue and was already fixed last week. We should close this issue?

**Comment by BrianAmadori** [comment]
chromium bug thread: https://bugs.chromium.org/p/v8/issues/detail?id=10957
unity thread: https://forum.unity.com/threads/webgl-player-broken-on-chrome-86-0-4240-75-unity-2019-4-12f1-lts.985397/
