### ISSUE TITLE
bug: Can't close the email dialog on some scenes

### ISSUE THREAD

**Issue by eordano** [decentraland/explorer#1429]
Reported on [Tominoya](https://play.decentraland.org/?position=-75%2C77)

Also reportedly happening in other scenes (maybe related to scene UIs? Tominoya is pretty heavy on them)

![image (1)](https://user-images.githubusercontent.com/42750/96003759-df2b9700-0e3a-11eb-9c08-412ed67b4146.png)

**Comment by BrianAmadori** [comment]
Duplicate of https://github.com/decentraland/explorer/issues/1418. Just added your description on that one.
