### ISSUE TITLE
It is difficult to lock the mouse after unlock it with the ESC key

### ISSUE THREAD

**Issue by sandrade-dcl** [decentraland/explorer#1478]
Reported by **Nico E:** If I press `ESC` to release the mouse, and I then click again to gain control again, I have to click several times to get it to work (**it is already happening in Production**).

It seems as if the browser does not detect the `pointerlockchange` event well.

**STEPS TO REPRODUCE IT:**

1. Press `ESC` key to unlock the mouse.
2. Try to lock the mouse again clicking in the world.
3. Notice that it is difficult to lock the mouse at first (you have to click several times).

**Comment by pravusjif** [comment]
Started testing a different aproach:
1. Detect input in kernel/browser side (click and ESC)
2. kernel tells Unity that a lock is requested -> unity checks if the cursor is over any HUD Panel or not, to confirm the locking or not

It's still WIP and temporarily paused.

**Comment by pravusjif** [comment]
After trying it all with our kernel being the one who starts this pointer lock/unlock, I created a basic HTML to test this in a more isolated way:
```
<!DOCTYPE html>
<html>
    <body>
        <canvas id="myCanvas" width="200" height="100"></canvas>
        <script>
            var element = document.getElementById("myCanvas");
            document.onclick = function() {
                console.log('onClick')

                // Ask the browser to lock the pointer
                element.requestPointerLock = element.requestPointerLock || element.mozRequestPointerLock || element.webkitRequestPointerLock
                element.requestPointerLock()
            }

            const handlePointerLockUpdate = () => {
                const isLocked = (document.pointerLockElement || document.mozPointerLockElement || document.webkitPointerLockElement) != null
                console.log('pointerlockchange - ' + isLocked)
            }

            document.addEventListener('pointerlockchange', handlePointerLockUpdate, false)
            document.addEventListener('mozpointerlockchange', handlePointerLockUpdate, false)
            document.addEventListener('webkitpointerlockchange', handlePointerLockUpdate, false)
        </script>
    </body>
</html>
```

If you test that code you will see that:
* In Firefox we can lock and unlock normally, and also quickly (unlock-lock rapidly) with no issues (this works fine with our explorer too, in Firefox)
* In Chrome, we can lock and unlock normally if we do it slowly, but if we try a rapid unlock-lock action, we get the exact same behaviour we are struggling with in our explorer: even though the browser detects the onclick event at the correct moment, it takes several seconds to allow a new locking.

So this is a problem with chrome that we cannot fix.
