### ISSUE TITLE
Position Scaling Issue on multiple instances of GLTF

### ISSUE THREAD

**Issue by jamesashton** [decentraland/explorer#1505]
As discussed with @nchamo  This google doc shows how the instances are created  and  running on preview:

https://docs.google.com/document/d/16t8W9jxZ_kEE1AnQyz0nWesaFdcqiU5jRXqCov1PYAc/edit

**Comment by jamesashton** [comment]
I will send @nchamo the scene in a DM as it's not open source.

**Comment by nchamo** [comment]
It looks like the release stopped hiding a bug in the scene code. Will close this, but @jamesashton please re-open it if the issue continues to happen.
