### ISSUE TITLE
Investigate if AvatarEditor camera to edit the avatar should be adapted as a new CameraMode

### ISSUE THREAD

**Issue by AjimenezDCL** [decentraland/explorer#155]
Research if AvatarEditor can take advantage of the new design for the multi camera system and adapt the current implementation to it.

**Comment by xpalaum** [comment]
@BrianAmadori is it worth investigating at this point? (if not obviously needed, we can save effort (3 points + TBD) on our way to Launch. Blocking for now, let me know.

**Comment by AjimenezDCL** [comment]
I would say to leave this for the future.

Ideally all camera systems would use a similar approach, but the current implementation is solid and it's working good. The investigation is to estimate the effort of adapting the avatar editor camera to the new paradigm and if it worth it.

**Comment by BrianAmadori** [comment]
This is not needed for now. As the camera modes are designed for in-world interaction and not so much for editor interaction, this would require a significant redesign. As we already fixed the avatar preview camera being active in-game, i'm closing it.
