### ISSUE TITLE
Implement free-mode camera when character is not moving.

### ISSUE THREAD

**Issue by AjimenezDCL** [decentraland/explorer#156]
Implement free-mode (rotate around the player) camera when character is not moving.

You can find more information about the feature and the design in the 1pgr.
https://docs.google.com/document/d/1bt_ph-9rTSNpgOdAeKDN5qWyQioa6pJ6WfB2VEFDgjc/edit#

**Comment by BrianAmadori** [comment]
I'll closing this because we are redesigning the camera polish using @MadRex prototype, and this doesn't involve this issue.
