### ISSUE TITLE
fix: pixelated avatars on top right corner 

### ISSUE THREAD

**Issue by eordano** [decentraland/explorer#173]
![1D0BC77D-E7C4-4A8D-9C66-012735046004](https://user-images.githubusercontent.com/42750/69890594-5c0e5a80-12d5-11ea-837c-646d6bc02976.jpeg)

This should be fixed by enabling mipmaps and trilinear filtering on avatar profile texture.

**Comment by nearnshaw** [comment]
@BrianAmadori 
I'd say this is fixed with the new Unity version, right?

**Comment by BrianAmadori** [comment]
Yep!, it should be fixed by now. Closing.
