### ISSUE TITLE
[Performance Error Banner] Make label next to checkbox clickable

### ISSUE THREAD

**Issue by eordano** [decentraland/explorer#1764]
Current behavior:
Clicking on `Don't show this again` is a no-op; nothing happens.

Expected behavior:
When one clicks on the text `Don't show this again`, this label should behave the same as clicking on the white box.

![image](https://user-images.githubusercontent.com/42750/101175019-67e8d700-3623-11eb-9191-c00c2ac7e857.png)

**Comment by menduz** [comment]
https://en.wikipedia.org/wiki/Fitts%27s_law
