### ISSUE TITLE
Removing entity from engine removes its components from memory, even if shared

### ISSUE THREAD

**Issue by BrianAmadori** [decentraland/explorer#177]
This code doesn't work. Once the box is removed from the engine, adding it again doesn't render it:

```
const box = new Entity();
box.addComponent(new BoxShape());
box.addComponent(new Transform({position:new Vector3(8,0.11,8)}));
engine.addEntity(box);
engine.removeEntity(box);
engine.addEntity(box);
```

Something similar happens if I tried to use the shape that was previously used by a removed entity on a new entity. It seems like when removing from engine, the shape component is no longer available.

Here we should see the box2 entity, but it can't find a shape to be rendered with.

```
const shape = new BoxShape();

const box1 = new Entity();
box1.addComponent(shape);

engine.addEntity(box1);
engine.removeEntity(box1);

const box2 = new Entity();
box2.addComponent(shape);
engine.addEntity(box2);
```

In this other scene we see something that's surely related, and might throw more light into this:
When clicking box 1 you toggle box 2 on and off, but at the 3rd attempt, all boxes disappear.

[add-remove-bug.zip](https://github.com/decentraland/unity-client/files/3498909/add-remove-bug.zip)

Weird fact:  If I add two more cubes to the scene (that don't do anything), I have to toggle the cube two more times to have it all break. It seems like we're losing one of the BoxShape components every time we remove the cube, and as long as at least one exists in memory the scene can work things out, until we run out of them.

**Comment by nearnshaw** [comment]
It looks like the second example, the one in the attached zip, is no longer happening, that's fixed.

But the first problem, is still happening:
```
const box = new Entity();
box.addComponent(new BoxShape());
box.addComponent(new Transform({position:new Vector3(8,0.11,8)}));
engine.addEntity(box);
engine.removeEntity(box);
engine.addEntity(box);
```
