### ISSUE TITLE
UV mapping of some models getting messed up

### ISSUE THREAD

**Issue by BrianAmadori** [decentraland/explorer#179]
Some models, specifically by Cybermike and Renderdog, used to work well (not sure how long ago), but now have the uv mapping different from what it used to be.

See attached a models that suffered this.
If you importing into the Babylon sandbox in https://sandbox.babylonjs.com/ you'll see that the texture looks different than if you use it in a scene

*Renderdog*:

[https://app.zenhub.com/files/154520831/93e29268-25d1-4df2-a556-83f16e95ca22/download](https://app.zenhub.com/files/154520831/93e29268-25d1-4df2-a556-83f16e95ca22/download)

from RenderDog

SDK has a bug and UV tiling does not work. Is that still the case? I am using blender and I am finding it does not work in DCL but it does on other platforms. In DCL I have been getting around this by having a ground terrain UV scaled beyond the 0-1 coordinates. 

*CyberMike*:

[Models-2.zip](https://github.com/decentraland/unity-client/files/3655200/Models-2.zip)

From Cybermike:

I think it was in version 6.1 onwards, somewhere inbetween 6.1 and current 6.4 (i think) is when this problem showed itself. Also when i do manage to do a work around of moving uv's back to the default channel of 1 (which have not been collapsed and lost) they appear SO DARK in the sdk, you cant see the texture, i had to over expose the texture in ps and it looks bad...  so the problem is uv mapping channel can not go greater then default 1, i think

**Comment by pravusjif** [comment]
I just tested the "RenderDog" glb in the UnityGLTF project (not our modified version) and its UVs are loaded correctly so we should check what we are doing differently or update a part of our GLTFSceneImporter based on their version (as we did with the animations parsing section).

Of course as we have heavily modified the importer, any update there is no simple task.

**Comment by AjimenezDCL** [comment]
We have two different issues here, this ticket will be closed and these two issues will me moved to new tickets:

_RenderDog_  #1389: I dont think this ever worked before, we have never supported UV scale/offset, _RenderDog_'s statement kinda confirms it.

_CyberMike_ #1390: This confuses me a lot, we have never supported anything but UV0s. Not even Khronos has it yet https://github.com/KhronosGroup/UnityGLTF/issues/93 https://github.com/KhronosGroup/UnityGLTF/blob/1e003333698be2d6026211c2ee85ddbd25d07b72/UnityGLTF/Assets/UnityGLTF/Runtime/Scripts/UniformMaps/MetalRough2StandardMap.cs#L20. 
So it's really strange that ever worked for him, we should doublecheck if that's the case.
 I was not able to reproduce his "appears dark" issue neither (comparing against Babylon's Sandbox)  but I have seen that the materials has a _dark grey_ albedo color; again this shouldnt be related to anything we did.
