### ISSUE TITLE
decentraland-ecs@6.6.1 causes errors in dcl build if scene uses eth-connect

### ISSUE THREAD

**Issue by cfravel** [decentraland/explorer#1811]
Create a scene that imports the eth-connect model, using decentraland-ecs@6.6.1
Run `dcl build` on it
See errors about dependencies
npm i decentraland-ecs@6.6.0
Run `dcl build`
no errors.

**Comment by nchamo** [comment]
May be fixed by https://github.com/decentraland/eth-connect/pull/19 and https://github.com/decentraland/eth-connect/pull/21

**Comment by menduz** [comment]
Can you paste the errors please? It is very difficult to diagnose "errors about dependencies"

**Comment by nchamo** [comment]
@cfravel , we just release version 5.0.0 of the eth-connect library

It has some breaking changes, so please refer to https://docs.decentraland.org/development-guide/scene-blockchain-operations/#lower-level-operations on how to use it. But it might make your errors go away.

If so, please close this issue 😄

**Comment by nchamo** [comment]
I'm closing this issue. @cfravel, if the problem persists, please re-open it
