### ISSUE TITLE
Animations don't play when not looking: breaks elevators & others

### ISSUE THREAD

**Issue by nearnshaw** [decentraland/explorer#1874]
Go to genesis plaza, hop onto an elevator while looking at the floor, it works

hop onto it while looking up (in 1st person) it doesn't work. Look down, it starts.

This used to happen months ago, it had to do with not playing animations that were not in sight
It had been fixed back then, but now it’s back
It’s in production and in @next

**Comment by BrianAmadori** [comment]
temporary fix applied on #1875
