### ISSUE TITLE
6.6.3 caused an issue with preview just failing to load if you change parcels in scene.json(have example)

### ISSUE THREAD

**Issue by FireFoxxG** [decentraland/explorer#1888]
See the image, but that is all it takes to break the scene so it doesn't load.  Confirmed with doug from nftworld.io

When the scene loads, it loads the structure fine, but when loaded with the 2 parcel list it fails to even load the previewer, (the model is within the bounds of the 2 parcels that fail).  4 also doesn't work. Only the 6 parcel list works, which was previously deployed a few months ago, with a different 2x3 parcel model.

![image](https://user-images.githubusercontent.com/30537370/103263414-13582380-4965-11eb-88bc-44c6bb356432.png)

**Comment by pravusjif** [comment]
fixed in https://github.com/decentraland/explorer/pull/1900
