### ISSUE TITLE
Fix shadows for the builder to fix Builder#779

### ISSUE THREAD

**Issue by eordano** [decentraland/explorer#19]
More info: https://github.com/decentraland/builder/issues/779
Reference: @belohlavek

**Comment by pravusjif** [comment]
- We could try playing with the 'shadow distance' in the LWRP settings.
- We could also check the 'shadow bias' in the light component (the directional light in the scene) itself
- We could also check if it's a problem of the ground projecting it's own shadow on itself or similar (as the ground is rendered a little bit lifted and not in Y == 0)

**Comment by eordano** [comment]
@pbosio can you close this issue if you deem it's done?

**Comment by pbosio** [comment]
> @pbosio can you close this issue if you deem it's done?

I was going to wait until I push a new version to the builder repo with that fix.
But I'll close this issue and keep the one in builder project open until I push the fix
