### ISSUE TITLE
Typo in TranformConstructorArgs  (missing an s)

### ISSUE THREAD

**Issue by nearnshaw** [decentraland/explorer#1908]
A type that's commonly used in the SDK has a typo
This type is very used when building abstract objects, to have position, rotation and scale all as a single property

It's called TranformConstructorArgs

It should be TransformConstructorArgs
Writing it correctly is marked as an error en VS Studio

It's tricky to correct this bc it would surely break a lot of existing scenes.  Any way we can keep compatibility w the typo'd version?
Or maybe a fix on this would only affect scenes that use newer SDK versions?  If so then that doesn't sound so bad.

**Comment by marcosnc** [comment]
I think this should be fixed by removing the typo in the current type and creating a new (deprecated) type as follows:

```
export type TransformConstructorArgs = {
  ...
}

/** @deprecated */
export type TranformConstructorArgs = TransformConstructorArgs
```

**Comment by nchamo** [comment]
Closed in https://github.com/decentraland/explorer/pull/1918
