### ISSUE TITLE
MessageBus only sends to myself, not other players

### ISSUE THREAD

**Issue by nearnshaw** [decentraland/explorer#1938]
The messageBus is only working to send messages to myself, but other players aren't getting those messages

I created a very simple scene to test this out:

All the code in the scene:

```ts
import utils from '../node_modules/decentraland-ecs-utils/index'
import * as ui from '../node_modules/@dcl/ui-utils/index'

let sceneMessageBus = new MessageBus()

let box = utils.addTestCube(
  { position: new Vector3(8, 0, 8) },
  () => {
    sceneMessageBus.emit('boom', {})
  },
  'BOOM'
)

sceneMessageBus.on('boom', () => {
  ui.displayAnnouncement('BOOM')
})
```

[https://app.zenhub.com/files/220994476/ba349636-06a7-4a8f-92fa-957cf0cfe68b/download](https://app.zenhub.com/files/220994476/ba349636-06a7-4a8f-92fa-957cf0cfe68b/download)

When I try this locally, I see the "BOOM" message in the UI when I click the cube. But if I open a second tab, the two players see themselves, but each only sees the "BOOM" from his own clicks, not from the other player.

I deployed this scene to a parcel I own myself, and the same happens in-world. If I open a second tab in Firefox, the players see each other, but each only sees the UI messages from their own clicks, not from the other player.

https://play.decentraland.org/?position=-133%2C-42&realm=fenrir-amber

Comms are working fine, if I go with my two tabs to another older scene that uses the message bus, it seems to work fine. Maybe the SDK broke something in one of the latest releases?

**Comment by pbosio** [comment]
Turns out that this code fragment

> let box = utils.addTestCube(
>   { position: new Vector3(8, 0, 8) },
>   () => {
>     sceneMessageBus.emit('boom', {})
>   },
>   'BOOM'
> )

 generates a race condition that ends up in an unhandled exception while resolving module `CommunicationsController`
