### ISSUE TITLE
QX-MPAPI: multiplayer API improvements

### ISSUE THREAD

**Issue by BrianAmadori** [decentraland/explorer#195]

**Comment by moliva** [comment]
@xpalaum @nearnshaw [There is an already existing document](https://docs.google.com/document/d/1FHt29dgFh7bvyHRmw7nUDLfvxBjgqOf4MSUbXsDInMg), do we plan to go any of these ways in particular?

**Comment by nearnshaw** [comment]
@moliva   I wrote that doc when the plan was different, and we were looking into having a single product that included spatial OS and all that

several ideas there still hold true, like reading the position of all players, lossy transform updates, and being able to easily label something as "synced"
but "server controlled movement" is something that would require quite a rearchitecture to incorporate, so surely not in the short term at least
