### ISSUE TITLE
NFTShape has no error handling

### ISSUE THREAD

**Issue by nearnshaw** [decentraland/explorer#1968]
If a scene creator provides the wrong data about an NFT (or probably also if the OpenSea API fails), this doesn't just break the loading of that particular NFT. It breaks the loading of all other NFTs in the scene, and perhaps also the loading of other things in the scene.

Here's a simple little example with two picture frames. The first is well created, the second has bad information on its path field:

```
const entity = new Entity()
const shapeComponent = new NFTShape(
  'ethereum://0x06012c8cf97BEaD5deAe237070F9587f8E7A266d/558536'
)
entity.addComponent(shapeComponent)
entity.addComponent(
  new Transform({
    position: new Vector3(4, 1.5, 4),
  })
)
engine.addEntity(entity)

const entity2 = new Entity()
const shapeComponent2 = new NFTShape(
  'ethereum://IDK WTF Im doing this is not a real contract name, I just wrote whatever/666'
)
entity2.addComponent(shapeComponent2)
entity2.addComponent(
  new Transform({
    position: new Vector3(8, 1.5, 4),
  })
)
engine.addEntity(entity2)
```

If I run this, none of the two paintings ever finish loading, they show the spinning wheel forever. If I comment out the second picture frame, the first one loads just fine.

Creators have often complained about this, because in a scene with many picture frames it's not rare to miss some digit, and it breaks them all. Finding the one that's incorrect can be a real pain if they all appear to be broken.

Ideally, if a request fails would be nice to also display some kind of error image instead of keeping the spinning wheel forever. Maybe something like the broken link icon.

**Comment by pbosio** [comment]
Just to give more insight about this issue:
We have a request limit to OpenSea's api
so we are joining several NFT in the same request (up to 20 I think)
if there is a problem with one of those NFT the api respond with an error so all NFTs that were added to the same request fail
