### ISSUE TITLE
doc: write technical design for v2 interaction specs

### ISSUE THREAD

**Issue by xpalaum** [decentraland/explorer#206]
Add interaction feedback when you get close to an object:
- [ ] Show small toast next to an interactive object when player gets close enough to it (both 1st and 3rd person camera mode).
- [ ] Toast includes an icon representing the key to press to interact with the object, and a configurable word (for ex: "collect", "break", "push").
- [ ] Change cross-hair when pointing at an object.
- [ ] Modify "keys" smart items so that they work with the feedback (with @cazala )

Parameters implementation:
- [ ] Add parameter to OnPointerX with the word representing the interaction ("Use" by default)
- [ ] Add parameter to OnPointerX with the key/button to press (key "E" by default).
- [ ] Add parameter to OnPointerX with the distance (short distance by default).

**Comment by BrianAmadori** [comment]
doc link: https://docs.google.com/document/d/1I2bcntDm3KIp2rO_J7cNIYQ94D2zrEG2-jY92wpfgBk
