### ISSUE TITLE
Eth connect issues with allowance function

### ISSUE THREAD

**Issue by nearnshaw** [decentraland/explorer#2098]
This was reported by Baus and his team

The problem seems to be new. It worked fine on eth-connect 4.0.2, but not in 5.0.0

The following snippet fails:

```ts
providerMatic = new EthConnect.HTTPProvider(maticRPCURL);
requestManagerMatic = new EthConnect.RequestManager(providerMatic);
const factoryMANA = await new EthConnect.ContractFactory(
    requestManagerMatic,
    ABIMANA
);
contractInstanceMANA = (await factoryMANA.at(
    manaTokenAddress
)) as any;
approved = await contractInstanceMANA.allowance(
    userWalletAddress,
    treasuryContractAddress
);
```

The problem is when calling allowance function.

> Uncaught (in promise) Error: invalid argument 0: json: cannot unmarshal invalid hex string into Go struct field CallArgs.data of type hexutil.Bytes

**Comment by menduz** [comment]
Test values for each variable are required to debug. Including contract addresses please

**Comment by tj0218** [comment]
@menduz can you drop your email here?
I will share via email.

**Comment by menduz** [comment]
Please share the details here, I will receive the email notifications.

I wrote specific tests for this specific issue, testing against geth and ganache. https://github.com/decentraland/eth-connect/pull/36/files#diff-d013a98cbb4e8036db3f6b5dd308d151b282e69fc327792dfe864020963efb04R182-R191

We need the specific request body you are sending to matic that is yielding that error, among with the _exact_ values you provided to the function call `allowance`.

**Comment by menduz** [comment]
PS: you can see what is being exchanged with matic to help us debug by writing `providerMatic.debug = true`
A new version of eth-connect was published for testing ([look at this PR](https://github.com/decentraland/eth-connect/pull/36)), please try to reproduce the issue installing `eth-connect@next`

**Comment by tj0218** [comment]
SEND >> {"jsonrpc":"2.0","id":6,"method":"eth_call","params":[{"from":"0x6224fe0bea79701d338cf65ebc0da0caa566c544","to":"0x11e46DB40d4438D1c64f68993CA43b03Ac1B6A6B","data":"0x39c2a5380000000000000000000000006224fe0bea79701d338cf65ebc0da0caa566c544"},"latest"]}

----------------------------------------------------------------------------------------------------------------------

RECV << {"jsonrpc":"2.0","id":4,"error":{"code":-32602,"message":"invalid argument 0: json: cannot unmarshal invalid hex string into Go struct field CallArgs.data of type hexutil.Bytes"}}

----------------------------------------------------------------------------------------------------------------------

I have tried to reproduce the issue installing `eth-connect@next`
My wallet address is 0x6224fe0bea79701d338cf65ebc0da0caa566c544.
And treasuryContractAddress is 0xBF79cE2fbd819e5aBC2327563D02a200255B7Cb3.

**Comment by menduz** [comment]
Please attack the whole debug log. The error corresponds to the RCP id 6, but you are only attaching the 4th (SEND & RECV things)

**Comment by tj0218** [comment]
Hey @menduz ,
I am adding a whole screenshot of my console logs.
![Screen Shot 2021-02-23 at 10 11 05 AM](https://user-images.githubusercontent.com/52079265/108872270-9c838380-75bf-11eb-8e57-aa4efc3a0443.png)

**Comment by menduz** [comment]
Ok, you should be able to provide me more data with that screenshot.

the lines with `SEND id: 3` `SEND id: 4` `SEND id: 5` in the middle of the console have a NaN at the end of the HEX

The contract is  `0xA1c57f48F0Deb89f569dFbE6E2B7f46D33606fD4` and the selector is `allowance(address,address)` => `0xdd62ed3e`

Could you print _exactly_ what you are passing to the allowance functions? (you are calling it three times by the way, beware of that since you _must_ execute it once per account)

**Comment by tj0218** [comment]
```
approved = await contractInstanceMANA.allowance(
        walletAddress,
        contractAddress
);
```

this is how I am calling allowance function.

**Comment by menduz** [comment]
I need the arguments. Print what you are passing to it

**Comment by menduz** [comment]
because it seems that contractAddress is an invalid value

**Comment by tj0218** [comment]
![Screen Shot 2021-02-23 at 10 46 48 AM](https://user-images.githubusercontent.com/52079265/108877093-83310600-75c4-11eb-9d21-57b1e66141b3.png)

```
-115,133:  walletAddress -------------------- 0x6224fe0bea79701d338cf65ebc0da0caa566c544
-115,133:  contractAddress ---------------  0xBF79cE2fbd819e5aBC2327563D02a200255B7Cb3

```

**Comment by menduz** [comment]
does it have a heading space? `[space]0xBF79cE2fbd819e5aBC2327563D02a200255B7Cb3`

**Comment by tj0218** [comment]
No.

**Comment by menduz** [comment]
try printing it with `JSON.stringify(contractAddress)` because it has tests working, and I have no clue on why is it being converted to NaN instead of a valid bignumber in your code

**Comment by tj0218** [comment]
```
-115,133:  walletAddress --------------------: "0x6224fe0bea79701d338cf65ebc0da0caa566c544"
-115,133:  contractAddress ---------------: "0xBF79cE2fbd819e5aBC2327563D02a200255B7Cb3"

```

Here you go.

**Comment by tj0218** [comment]
```
approved = await contractInstanceMANA.allowance(
      "0x6224fe0bea79701d338cf65ebc0da0caa566c544",
      "0xBF79cE2fbd819e5aBC2327563D02a200255B7Cb3"
    );
```
I changed the code like this and tried again but got same result.

**Comment by menduz** [comment]
Nailed it, it was a wild bug. For some reason the upper case of the address made the big number library fail. I'm pushing a fix now. In the meantime, could you try with a `walletAddress.toLowerCase(), contractAddress.toLowerCase()` to see if it works?

**Comment by tj0218** [comment]
OK!

**Comment by menduz** [comment]
Here is the fix, in case you wonder. It should be available for you in some minutes installing it with `@next` https://github.com/decentraland/eth-connect/pull/38

**Comment by menduz** [comment]
Fixed, we can close the issue. I can't find the "close issue" button in the mobile app
