### ISSUE TITLE
Show tips on the error screen when players can't log in

### ISSUE THREAD

**Issue by RominaMarchetti** [decentraland/explorer#2115]
The error screen should give a clue of what is happening when players can not enter. "LEARN MORE" takes the players to the following link: https://docs.decentraland.org/decentraland/hardware-acceleration/

Figma link: https://www.figma.com/file/akmeRX6da0lnNuJuN50eMC/LoadingErrorsScreens?node-id=554%3A39

![LogInError.png](https://images.zenhubusercontent.com/5d91f7e9df37660001a11578/9732ce99-883c-4be3-a8e3-0794fdd1fe1d)

**Comment by nearnshaw** [comment]
Copy suggestion:

Something went wrong

If you have any ad blocking extensions, try turning them off for this site.

Loading should not take any longer than 2-3 minutes. If you seem to be stuck, make sure hardware acceleration is on.

**Comment by marcosnc** [comment]
This was done in this PR: https://github.com/decentraland/explorer/pull/2118
