### ISSUE TITLE
Integrate proper toast feedback with the new OnPointerEvent fields

### ISSUE THREAD

**Issue by BrianAmadori** [decentraland/explorer#218]
This section should cover the `Implementing the Hover toast UI` part of the TDD and wiring of the toast parameter fields of the OnPointer events.
https://docs.google.com/document/d/1I2bcntDm3KIp2rO_J7cNIYQ94D2zrEG2-jY92wpfgBk/edit#heading=h.tnb97qmxu28a

We need the hover feature finished and Romi's final toast design in order to implement this.

-----

Toast message structure: objects’ name plus command/s action/s

1st person camera

![image.png](https://images.zenhubusercontent.com/5d91f7e9df37660001a11578/68b2dc69-eaa0-475d-8f8e-a7c9a9bf5b01)
![image.png](https://images.zenhubusercontent.com/5d91f7e9df37660001a11578/14349d3b-f837-4aed-9908-a7aa873c61fe)
3rd person camera

![image.png](https://images.zenhubusercontent.com/5d91f7e9df37660001a11578/d32ece71-3421-432a-ba0b-c9803c6f3ab3)
![image.png](https://images.zenhubusercontent.com/5d91f7e9df37660001a11578/ccb1bc3d-76d8-4885-8749-ca0bcf094061)

**Comment by pravusjif** [comment]
I'm closing this issue as this has been tackled in 
https://app.zenhub.com/workspaces/explorer-5dc988c462b0b700019b0b42/issues/decentraland/explorer/216

I can't remove the estimation so i'm changing it from 8 to 1
