### ISSUE TITLE
Offline/online not working properly for friends

### ISSUE THREAD

**Issue by nchamo** [decentraland/explorer#2222]
We have had reports that the the state of friends (offline/online) is not working correctly. This might be a bug on the Matrix side of things, but we need to investigate it.

**Comment by eordano** [comment]
Yes, this seems to be happening 100% of the time (doesn't work for me and a few others on discord)
![image](https://user-images.githubusercontent.com/42750/111856948-00724100-890d-11eb-97ec-f7b64bf997eb.png)

**Comment by nchamo** [comment]
The problem was on the Matrix server. It has been fixed now
