### ISSUE TITLE
Q1-XN: Label ownership of multiple collectibles of the same type as "x2", "x3", .... "xN"

### ISSUE THREAD

**Issue by xpalaum** [decentraland/explorer#234]
Add an indicator of the number of items of the same type to the Inventory. This is needed as soon as players can have more than one, which can already be the case through buying on Open Sea. It will become less rare as we introduce features like Login Sweepstakes, or as we launch our own Marketplace for NFTs.

**Decentraland indicator**

![image.png](https://images.zenhubusercontent.com/5d91f7e9df37660001a11578/fb5cf58b-a1ef-44b9-864a-986ff35a1f3f)

When users opens Info Card of an item that has more than one of the same type, a pager appears at the bottom of it with next/previous buttons and cards indicator (now is not possible to interact that way, because when living info hover the info card disappears. We need to fix it).

**Decentraland Avatar Editor**

![image.png](https://images.zenhubusercontent.com/5d91f7e9df37660001a11578/af7171a1-0182-4e5a-83f0-af419dd7c01c)

**Inspired on Hearthstone**

![xN.png](https://images.zenhubusercontent.com/5d91dca0703cca0001efbe30/a044344d-fefb-4cd9-8364-f090348b8160)

**Comment by BrianAmadori** [comment]
Not sure if this should be an MVP feature, or at least shouldn't be more important than performance/UX/game feel stuff.

**Comment by xpalaum** [comment]
This should not be a lot of effort, hopefully, and not having it can be seen as a bug. What if you have 5 instances of the same wearable NFT (this will be common sooner than later next year). Both not showing them all or showing them separately is a bad user XP. We need to display wearables correctly also because players will be able to put each of them for sale on our Marketplace.

I agree the priority was a tad high, tweaking now.
