### ISSUE TITLE
Report fatal and scene errors to segment

### ISSUE THREAD

**Issue by eordano** [decentraland/explorer#24]
Ensure that all the error states reported to redux are being transmitted!

**Comment by eordano** [comment]
@dnul can you verify this is working?

**Comment by dnul** [comment]
last error_fatal was on 2019-11-11 and is sent through the loading_funnel, total of 3 were received all time. 

this are all errors I have records of 

error_comms_1
error_comms_2
error_comms_3
error_comms_4
error_comms_failed
error_fatal
error_fetchengine

is there any way I can recreate a fatal_error to test this?

**Comment by BrianAmadori** [comment]
According to @moliva this should be already addressed. Need to revalidate.

**Comment by eordano** [comment]
Correct

https://rollbar.com/decentraland/World/
