### ISSUE TITLE
Spike: Client comms breakdown

### ISSUE THREAD

**Issue by xpalaum** [decentraland/explorer#249]
When many people gather together in one scene, the client may start "breaking down" showing a few of these symptoms:

- Missing Avatar name tags
- Chat not working or very laggy
- Interactive objects not working or very laggy
- Not seeing other players / any other players

In the last months, optimizations like Wasm<>JS Serialization going from JSON to binary had the potential to remove such bottlenecks. I was hoping Platform/Infra would become the weakest link.

This issue describes the problem and suggests spending a timebox to investigate why are comms still so limited on the client side.

**Comment by xpalaum** [comment]
Added dependency with new comms system. This issue is about testing if we can reproduce what is described with the new system (it should support up to 8 players in one interactive scene, ideally more).

**Comment by BrianAmadori** [comment]
Closing this because it doesn't address anything in particular. If any of those issues arises again, let's open the corresponding issue and address it in our sprint working flow.
