### ISSUE TITLE
Example scene no longer clickable

### ISSUE THREAD

**Issue by nearnshaw** [decentraland/explorer#286]
This example scene has an issue in .zone
https://explorer.decentraland.zone/?position=55%2C-69

When I click on the wheels, they should start spinning. The toast says they are interactive, but when I click nothing happens

If I run it locally using the @latest SDK version, it works well
but if I use the @next version, it doesn't work anymore

https://github.com/decentraland-scenes/Hypno-wheels

Perhaps this is unrelated, but this scene from the past Game Jam seems to be affected by the same bug, none of the items in it respond to clicks anymore
https://explorer.decentraland.org/?position=-28%2C-3

**Comment by pravusjif** [comment]
After checking **Neo Arcadia -29,-4** and the "stage with spinning circles" we have in zone near **-54,70**, debugging from the editor I was able to see they have colliders covering the entities that have the PointerDown/PointerUp (the arcades in Neo Arcadia and the stage in example scenes in Zone).

So the fix here is to modify the models and entities to not have a collider on top of the desired OnPointerDown/OnPointerUp
