### ISSUE TITLE
Loading and runtime crashes

### ISSUE THREAD

**Issue by xpalaum** [decentraland/explorer#295]
https://explorer.decentraland.org/?position=76%2C-43

We should debug/fix this, it is possible it is not scene specific?

NEO DCL CITY, perhaps general:
![image.png](https://images.zenhubusercontent.com/5d91dca0703cca0001efbe30/1524c956-dd69-4e8a-ac98-06ea46e0d180)

I got the following in NEO DCL CITY and also in a scene next to Sugar Club. Looks like a general issue:
![image.png](https://images.zenhubusercontent.com/5d91dca0703cca0001efbe30/d29afd69-7b61-4b13-a0d8-4fbabfa1dc46)

**Comment by xpalaum** [comment]
More info:
![image.png](https://images.zenhubusercontent.com/5d91dca0703cca0001efbe30/25c8b521-019b-4c3a-bba3-60fb525cb590)
@pravusjif

**Comment by pravusjif** [comment]
I can't reproduce this bug =(

**Comment by pravusjif** [comment]
We just tried doing a "photoshot" with Shibu and other 5~ and almost everyone had this crash =(, I'm attaching new logs similar to the previous ones

![Screen Shot 2020-01-10 at 14.06.43.png](https://images.zenhubusercontent.com/5d9200f4f58e25000108abac/600009f1-cae5-41ce-9c13-44715702e94e)

![Screen Shot 2020-01-10 at 14.06.53.png](https://images.zenhubusercontent.com/5d9200f4f58e25000108abac/bab3d3f8-84a8-4c4e-aedd-873e9723fa20)

![Screen Shot 2020-01-10 at 14.06.35.png](https://images.zenhubusercontent.com/5d9200f4f58e25000108abac/d083f345-8f4a-4821-8cb0-fad26e4605da)
