### ISSUE TITLE
feat: visualize Rarity in Avatar editor

### ISSUE THREAD

**Issue by eordano** [decentraland/explorer#30]
Implement the frame color by rarity in the existing view.

![image.png](https://images.zenhubusercontent.com/5d91f7e9df37660001a11578/24bf72e7-fcff-4ba6-a31a-992e467c7d66)

**Comment by xpalaum** [comment]
Added mockup. In this story we implement the frame color by rarity, in the existing view.

![image.png](https://images.zenhubusercontent.com/5d91dca0703cca0001efbe30/603a3d5e-9a60-409a-9d2b-1d4d910b4b64)
