### ISSUE TITLE
Add cursor interaction feedback when clicking an avatar should display the player's info card

### ISSUE THREAD

**Issue by xpalaum** [decentraland/explorer#310]
When players approaches and aims an avatar for 1 sec, the toast with interaction input appears. That's the way players can check out other players' passport, waring collectibles, and moderation options. To close the card, click on close button.

1 pgr: https://docs.google.com/document/d/1YWRO9Ydkj3UknUw7ca7CQIrpy2Otwzsx8VcvhkhgxWE/edit#

The Player's Info Card has the 3 tabs and you can switch tab, but their content & functionality is in separate issues. 

![image.png](https://images.zenhubusercontent.com/5d91f7e9df37660001a11578/87c810f6-6848-4d4e-a73a-8499bfc5f8af)
![image.png](https://images.zenhubusercontent.com/5d91f7e9df37660001a11578/6388aa80-7926-45a4-b94a-8fc4763db6e3)

**Comment by xpalaum** [comment]
@BrianAmadori - We cannot close this issue yet. A key implementation is missing, which makes the whole Avatar Interactions feature hard to discover by the average player.

To do: **When a player approaches and aims another avatar for 1 sec, the toast with interaction input appears and crosshair reacts, same as with objects interactions**. (copied here from the 1pgr).

To see how it should look like, please check the image preview in the description above.

**Comment by BrianAmadori** [comment]
Thanks @xpalaum. Updated title to reflect better the intention of the issue.
