### ISSUE TITLE
Player Profile: Add info button to collectibles tab

### ISSUE THREAD

**Issue by xpalaum** [decentraland/explorer#313]
Here we have working Info Buttons for the Collectibles Tab.
Same UI/UX as Info Buttons on your own Edit Avatar menu.

**Note:** this is not mandatory for the MVP. If effort > 1 let's not do it now.

**Comment by xpalaum** [comment]
@AjimenezDCL I don't see the `info button to see details on collectibles worn by other avatars` currently live. Can you confirm it still needs to be done?

**Comment by BrianAmadori** [comment]
Closing because this is already done.

**Comment by xpalaum** [comment]
@BrianAmadori I just tested it and it does not seem to be done. Moving to "Review".

![image.png](https://images.zenhubusercontent.com/5d91dca0703cca0001efbe30/099a7e79-df98-4a51-a499-e92481799d93)

**Comment by marcosnc** [comment]
Closing this issue for now. This task will be taken when we revisit all this interface.
