### ISSUE TITLE
NUX-11: Welcome to X toast

### ISSUE THREAD

**Issue by xpalaum** [decentraland/explorer#321]
Trigger this toaster, using the existing toaster notifications system.

![welcome.png](https://images.zenhubusercontent.com/5d91dca0703cca0001efbe30/25b20e51-62ec-43b0-92c1-b767e8d700ad)

**Comment by pbosio** [comment]
This "wellcome" toaster should appear every time user enters Decentraland? or is it just for the NUX?

**Comment by xpalaum** [comment]
Ideally every time user enters DCL or teleports somewhere.
If this is not trivial, MVP is just for NUX.
