### ISSUE TITLE
fix: scene life cycle - player should not be able to enter scene until loaded

### ISSUE THREAD

**Issue by xpalaum** [decentraland/explorer#328]
Related to #260 and #182. Opening new issue with a more generic description, since I am not sure what is the root cause. But I'm getting reports of this happening in .org

Initial Loading can now can open the world even if the target scene has not fully loaded, including colliders.
There should be no timeout allowing that.
Better keep loading (if it's still making progress), retry, or eventually show an error screen.

![image.png](https://images.zenhubusercontent.com/5d91dca0703cca0001efbe30/269f8890-e595-4f5c-af78-1175a4d73850)

**Comment by BrianAmadori** [comment]
Closed old issue as it was a dupe. The description was:

>Right now, kernel waits 30 seconds to send an ActivateRendering state to the renderer.
>
>In some cases, the renderer is not ready to start when this callback is received. Leading to states where you aren't teleported correctly and the only thing you see is green boxes. When this happens, there's nothing to do and when the loading is actually finished you can get stuck inside a mesh (like i.e. genesis plaza).
>
>To fix this, we have to make sure kernel doesn't send the ActivateRendering timeout if the current scene isn't ready yet. We can add some text feedback to the loading screen to say the loading may take more than expected in this case.
