### ISSUE TITLE
Tech Design Doc: Inventory System for Edit Avatar + Trading (with DCL Vault)

### ISSUE THREAD

**Issue by eordano** [decentraland/explorer#34]
Related documents: 

- [PRD: Decentraland Vault](https://docs.google.com/document/d/12X_5KFnRkUrV0IikJ5-dUNpvVRCdiXzDCwhQxphvK-4/edit)
- [What is a wallet/different wallet models](https://docs.google.com/document/d/1r548ldhyvv6nmPdp8HbziBdzxpuXQoTJ0ArAoNYNmpQ/edit#heading=h.5mfkzbi366hl)

**Comment by eordano** [comment]
Can we get a link? Or did you work on top of the PRD? @AjimenezDCL

**Comment by AjimenezDCL** [comment]
@eordano 
Everything is at the bottom of this documment: https://docs.google.com/document/d/1CBRQJLjcGvSk6dueiLwl74SL7nebqwHbatf0BA7uVF8/edit
