### ISSUE TITLE
Interactive items not interactible in-world

### ISSUE THREAD

**Issue by nearnshaw** [decentraland/explorer#373]
This Builder-build scene works perfectly well when running it locally w the CLI or when running a preview on the Builder
But deployed to Zone, several things don't work
https://explorer.decentraland.zone/?position=63%2C-67

- puedo levantar la llave, pero no abrir la puerta principal con ella (nada raro en consola)
- si abro la tablet para ver texto, debería poder cerrarla con clickear en cualquier lado, sin liberar el cursor, pero no… tengo que liberar el cursor para poder clickearla (nada raro en consola).  

(try importing to Builder to see it,  or ask me for the SDK code of the scene to try it on the CLI)
[https://app.zenhub.com/files/220994476/3db915ac-d99d-440f-8652-6d0ca15d3f4d/download](https://app.zenhub.com/files/220994476/3db915ac-d99d-440f-8652-6d0ca15d3f4d/download)

A possibly better example:  The Quest of the Alcoholic Scarecrow

If I walk up to the scarecrow in the Builder preview he runs away 
https://builder.decentraland.org/view/pool/2983c81a-b18a-40cb-b829-a2400a48d66b?position=6%2C1

But not in-world
https://explorer.decentraland.org/?position=-8%2C-26

**Comment by pravusjif** [comment]
The builder has an out-of-date "frozen" version of the sdk, that probably has some implementations out-of-date, this is probably the reason it works in the builder

**Comment by nearnshaw** [comment]
I'm pretty sure that the reason this scene in particular isn't working is this 

Nico E 9:55 AM
just realized #375 is an issue with all global click events elsewhere too
you can see that global clicks don’t work in the basic interaction scene either
https://explorer.decentraland.zone/?ENABLE_WEB3&position=54%2C-71
and it would also explain #373, because using a key requires a global click event in the background
So the specific scene I reference in #373 is likely fixed by #375
but with that ticket I was trying to also bring awareness of something a lot more generalized and a lot harder to reproduce, that I’ve intermittently scene in a lot of Builder scenes
I thought this scene was a clear example of that, but it’s likely just the global clicks
I can think of other examples where this does occur, in-world
