### ISSUE TITLE
Global button events aren't working on some scenes

### ISSUE THREAD

**Issue by nearnshaw** [decentraland/explorer#375]
In the basic interactions scene, none of the spheres turn green. They're supposed to respond to global click events but don't. This issue is pretty recent. Worked Friday morning, at some point stopped working

https://explorer.decentraland.zone/?position=54%2C-71

This scene has a very new recent issue:
Castaway 2048 (https://explorer.decentraland.zone/?position=53%2C-70)

https://github.com/decentraland-scenes/Castaway-2048

I first experienced it on Friday, it used to work on Zone.

It actually works well when running it locally in a preview using next. But not when deploying that same scene.

The issue: Once you open the chest and start the game, you should be able to click, drag the mouse and release to tell the game to shift all gems up-down-left-right. Right now, doing this has no effect on the gems at all. There aren't any error messages in console either, things simply don't move anymore

**Comment by pravusjif** [comment]
Global button events have been fixed in this PR by Brian
https://github.com/decentraland/explorer/pull/386

(https://app.zenhub.com/workspaces/explorer-5dc988c462b0b700019b0b42/issues/decentraland/explorer/386)
