### ISSUE TITLE
AIR: Loot Crate logic smart item final

### ISSUE THREAD

**Issue by xpalaum** [decentraland/explorer#377]

**Comment by BrianAmadori** [comment]
What's this about?

**Comment by AjimenezDCL** [comment]
I thought this issue was about triggering the panel when the Airdrop request was triggered.
I believe this is the actual logic of the smart item to trigger the said AirdroppingRequest.

 @eordano can you estimate it?

**Comment by xpalaum** [comment]
It was about having the smart item all done, including what Alex commented. I think it is? Moving to Review column just in case. @nearnshaw @eordano
