### ISSUE TITLE
NUX-12: Ask for email the first time a reward is received

### ISSUE THREAD

**Issue by xpalaum** [decentraland/explorer#402]
Defined in Onboarding Experience: https://docs.google.com/document/d/1Bck5zQNC0MnTpQLNJaVtM36zYx4h3vpeAq8E4LzmQkQ/edit#heading=h.acj3p722hc2

### Daily Reward
Here we just need to hook DLS (daily login reward) feature into the NUX flow.

### Ask for Email
There are two cases:
• Alice (wallet connected)
• Bob (no wallet)

**1. Alice (wallet connected)**
After clicking "Collect" at the end of the Daily Login Reward flow, a toaster notification tells Alice that the collectibles are on the way to her inventory, and then a pop up window asks her to enter an email so that send her notifications about the collectibles’ status

![image.png](https://images.zenhubusercontent.com/5d91f7e9df37660001a11578/e9e22345-63cc-4b41-be71-5d1c315d6932)

**2. Bob (no wallet)**
Right after the welcome to Genesis Plaza toaster (Fig. 6) is gone, a popup appears to ask him for his email address since we would like to give him NFTs and need to send him a quick guide on setting up a wallet

![image.png](https://images.zenhubusercontent.com/5d91f7e9df37660001a11578/86532aeb-c418-4031-b210-c4a8625e07ae)

**Comment by eordano** [comment]
Missing a way to cancel/dismiss modal?

**Comment by BrianAmadori** [comment]
This can only be implemented as part of the Daily Rewards epic. I'm adding it there so we implement it when the Daily Rewards are in progress.

**Comment by xpalaum** [comment]
Yes, we need a close "X" button. @RominaMarchetti

**Comment by RominaMarchetti** [comment]
@xpalaum done and updated.

**Comment by pravusjif** [comment]
The prefab has been integrated into the explorer client but this should be triggered after the airdrop reward that comes after the tutorial, which is blocked right now by missing implementations in Kernel, apparently
