### ISSUE TITLE
Preview gets stuck on loading screen

### ISSUE THREAD

**Issue by nearnshaw** [decentraland/explorer#427]
When using the @next version of the CLI, running a preview w `dcl start, it never gets past the loading screen:

![Screen Shot 2020-02-06 at 16.41.31.png](https://images.zenhubusercontent.com/5d9b940e491c060001c8647b/b20461c6-91f9-492a-bf08-982283e08bba)

**Comment by eordano** [comment]
This is now done by 6.4.7
