### ISSUE TITLE
AssetBundles not being loaded a lot of the time

### ISSUE THREAD

**Issue by nearnshaw** [decentraland/explorer#430]
When walking around the world, both in org and zone, I see a lot of messages in the console warning about asset bundles not being able to be loaded, and having to fallback on an uncompressed version of the asset. 

In zone it happens constantly. In Org it also happens a lot, I suspect it's more with new scenes.

I believe this must have an impact on scene load time.

![Screen Shot 2020-01-27 at 09.52.59.png](https://images.zenhubusercontent.com/5d9b940e491c060001c8647b/96e5aae3-77bd-4b47-80ff-0da2f689f520)

**Comment by BrianAmadori** [comment]
This can be because those assets aren't converted to AB yet or the server isn't returning an error code and the request is trying to be resolved anyways.

**Comment by BrianAmadori** [comment]
This should have been addressed by now as most of the scenes should have been be converted. In the future let's open an issue with concrete coords if it happens again.
