### ISSUE TITLE
Different GLTF with external images of the same path can conflict each other.

### ISSUE THREAD

**Issue by nearnshaw** [decentraland/explorer#431]
DCL plazas had an issue where he first uploaded a version 1 of a model

Then changed it and uploaded a version 2, with the same name.

Version 2 when running `dcl start` locally looks as it should
![image.png](https://images.zenhubusercontent.com/5d9b940e491c060001c8647b/0e050cfb-9e66-4347-9cbd-d9ba5aa70249)

But in-world it still looks like version 1
![image.png](https://images.zenhubusercontent.com/5d9b940e491c060001c8647b/fcfcdb55-a39f-4055-8ef1-4188e334cd24)

With help from Carl Fravel, he changed the file names and redeployed, and the issue was fixed in that location.

A weird detail is that he has the same type of scene depoloyed to many locations, but each one with different images (since they want to show ads in each). But all of these are fetching the same 3D model, and they all look the same now.

Images are stored as separate files from the .gltf, so that's likely the root of the problem. From disussions w Brian, textures are being stored by path rather than hash, that would explain why we're replacing one with another.

**Comment by BrianAmadori** [comment]
The different meshes should resolve to different `Qm` hashes, and that should be enough to be differentiated by the AssetBundle/GLTF fallback. If the different models resolve to the same `Qm` hash then we have a serious issue.
