### ISSUE TITLE
AGR: Terms of Service Agreement

### ISSUE THREAD

**Issue by xpalaum** [decentraland/explorer#469]
1pg: https://docs.google.com/document/d/1auV1aO2lLKeXcxAH_KGhguFFRVVmw3hch4zyvndoh5s

This includes:

1. Show popup to players as they enter such scenes
Note: the Unity part of this was fully implemented by @AjimenezDCL. Instructions to test it are here: https://github.com/decentraland/explorer/pull/491

![image.png](https://images.zenhubusercontent.com/5d91dca0703cca0001efbe30/1f54b4b8-2898-438d-a0bd-5e9fffd55d10)

2. Builder / CLI option to flag scene as "Adult 18+" or "Betting" (final copy TBD).

![image.png](https://images.zenhubusercontent.com/5d91dca0703cca0001efbe30/5191512a-da0d-42d0-9794-5ac095d394a5)

**Comment by BrianAmadori** [comment]
The MVP of this is already in place. Let's create another epic if we want to give it a new spin.
