### ISSUE TITLE
(closed - replaced by multiple other issues)

### ISSUE THREAD

**Issue by eordano** [decentraland/explorer#49]
Fix all the Unity Tests

**Comment by pravusjif** [comment]
- Failing tests:
     + SceneTests -> the coroutine processing the messages in the Global Scene bus is stopping mid-test, we still don't know why. The tests pass individually
    + LoadableShapesTests -> GLTFShape_Tests -> PreExistentShapeUpdate
    + LoadableShapesTests -> Tests -> LoadableShapesTests -> PreExistentShapeUpdate
    + MaterialTransitionControllertests -> MaterialTransitionWithGLTF
    + MaterialTransitionControllertests -> MaterialTransitionWithParametrizableMeshes
    + AudioTests -> Tests -> AudioTests -> AudioComponentMissingValuesGetDefaultedOnUpdate
    + BillboardTests -> Tests -> BillboardTests -> CheckLookAtPlayer
    + AvatarShape_Tests -> Tests -> AvatarShapeTests -> NameBackgroundHasCorrectSize
    + AvatarShape_Tests -> Tests -> AvatarShapeVisualTests (I didn't even run it as we already know the problems we have with visual tests today)
    + UIContainerRectTests -> Tests -> UIContainerRectTests -> TestParenting
    + VisualTests (I didn't run them as we already know the problems we have with visual tests today)

-----------------------

* The “PreExistentShapeUpdate” that fail report the same error (something about loading the damaged helmet gltf), and apparently we have 2 sets of the same GLTf tets, maybe we can remove one of the 2 sets.
* “MaterialTransitionControllertests” report a null reference exception
* The Audio test reports a wrongly asserted float
* The billboard test reports a problem with the used model
* “AvatarShape_Tests” reports a problem with the avatar name size
* “UIContainerRectTests” reports a wrongly asserted bool

**Comment by BrianAmadori** [comment]
This issue should represent all the work done in tests in sprint 9. Sprint 10 test fixing is covered by the sprint 10 `Test Fixing` issues.
