### ISSUE TITLE
DLS: add info button to show probabilities

### ISSUE THREAD

**Issue by xpalaum** [decentraland/explorer#504]
Info button, on mouse hover it displays the following text: “Chances: 1% Legendary, 5% Epic, 10% Swanky, 14% Uncommon, 70% Empty.”

1pg: https://docs.google.com/document/d/16gBeK1v5wrNBIs2Imagxh1SwjQzpRqolgQ5VQQEhVS4

**Comment by BrianAmadori** [comment]
Closing stale issue. I figure we will create new issues related to this when this feature is re-introduced.
