### ISSUE TITLE
DLS: New UI for getting feedback and rewards

### ISSUE THREAD

**Issue by xpalaum** [decentraland/explorer#505]
https://docs.google.com/document/d/16gBeK1v5wrNBIs2Imagxh1SwjQzpRqolgQ5VQQEhVS4
use case #3

the UI previews will be pasted here ina few hours, once ready.
@RominaMarchetti

**Comment by BrianAmadori** [comment]
Closing stale issue. I figure we will create new issues related to this when this feature is re-introduced.
