### ISSUE TITLE
(invalid)

### ISSUE THREAD

**Issue by AjimenezDCL** [decentraland/explorer#51]
Old board issues: 

https://app.zenhub.com/workspaces/world-5d8ba4a04da3400001fc292f/issues/decentraland/unity-client/1129
https://app.zenhub.com/workspaces/world-5d8ba4a04da3400001fc292f/issues/decentraland/unity-client/1144

**Comment by eordano** [comment]
Replacing by https://github.com/decentraland/explorer/issues/55 and https://github.com/decentraland/explorer/issues/54
