### ISSUE TITLE
Entities render out of place

### ISSUE THREAD

**Issue by nearnshaw** [decentraland/explorer#521]
If I walk while a large scene is loading, several of the entities in the scene appear to be shifted to another location, outside the scene's position

Go to https://explorer.decentraland.zone/?ENABLE_WEB3&position=58%2C-65 and walk south west quickly while the larger scenes load, you're likely to see things out of place

Theory: This could be related to how the entire set of local coordinates is shifted as the player moves so that the player is in 0,0. ...  maybe the positioning of entities isn't taking this shift into account?

**Comment by BrianAmadori** [comment]
This should have been fixed with the pool's cleanup fix.
