### ISSUE TITLE
BodyShape selection in Avatar Editor defaults to wrong assets

### ISSUE THREAD

**Issue by eordano** [decentraland/explorer#54]
When you select a Body Shape, it should default to the same wearables as the bodyshape thumbnail (right now defaults to some random assets).
Also, and this is important, both bodyshapes defaults to no hair, they are both bald, that shouldn't happen.

<img width="1652" alt="Screen Shot 2019-11-07 at 11 47 49 AM" src="https://user-images.githubusercontent.com/18174992/68399250-e5a68e80-0154-11ea-9d2d-d0868311005b.png">
<img width="1632" alt="Screen Shot 2019-11-07 at 11 47 56 AM" src="https://user-images.githubusercontent.com/18174992/68399258-e808e880-0154-11ea-8ec3-f6bf9b071e12.png">

**Comment by eordano** [comment]
@xpalaum can you check this is fixed on `.zone` and close this issue?

**Comment by xpalaum** [comment]
Yes, it works!
