### ISSUE TITLE
Ghost avatar with old profile

### ISSUE THREAD

**Issue by eordano** [decentraland/explorer#559]
![image](https://user-images.githubusercontent.com/42750/74625199-46693e00-512a-11ea-81d0-c4ac5a311b74.png)
```{"userId":"0xbd23f82ee95e0ab4c46a062364b21eeeb3d58264","identity":{"ephemeralIdentity":{"address":"0x6dF4c42a9F74154DC74e4Ad5951E6570962756AE","privateKey":"0x04f38645d699a58c073b704187b84f55867eec59d81e97cc77015981abe7f0f0","publicKey":"3a2584bb092ba73a03489eb23a6f2cf809e8c075232abda118dbf0897cc3ee7c8daaeedc26682a20b0e3676e4b14570263b62c8a437d5eff63036f88ed8a19bc"},"expiration":"2020-02-24T05:06:13.169Z","authChain":[{"type":"SIGNER","payload":"0xBd23f82EE95e0AB4C46A062364B21eEEb3d58264","signature":""},{"type":"ECDSA_EPHEMERAL","payload":"Decentraland Login\nEphemeral address: 0x6dF4c42a9F74154DC74e4Ad5951E6570962756AE\nExpiration: 2020-02-24T05:06:13.169Z","signature":"0xc1005ce3e904983c194a036f74904597f67da0ec3ad4dda3d135eb404ba13e37702a612bf785c0f5ba05a18eb9e4f7b8b477aac88ac7fa5a44e99f950bbfeb301b"}],"address":"0xbd23f82ee95e0ab4c46a062364b21eeeb3d58264","hasConnectedWeb3":true},"version":3,"profile":{"tutorialStep":1,"userId":"0xbd23f82ee95e0ab4c46a062364b21eeeb3d58264","email":"","name":"RichardFeynman","hasClaimedName":true,"description":"Scientist, teacher, raconteur, and drummer.","ethAddress":"0xbd23f82ee95e0ab4c46a062364b21eeeb3d58264","version":3,"avatar":{"eyeColor":{"r":0,"g":0,"b":0,"a":1},"hairColor":{"r":0,"g":0,"b":0,"a":1},"skinColor":{"r":0,"g":0,"b":0,"a":1},"bodyShape":"dcl://base-avatars/BaseMale","wearables":["dcl://base-avatars/black_jacket","dcl://base-avatars/hip_hop_joggers","dcl://base-avatars/citycomfortableshoes","dcl://base-avatars/cool_hair","dcl://base-avatars/eyes_00","dcl://base-avatars/eyebrows_00","dcl://base-avatars/mouth_00","dcl://base-avatars/beard","dcl://base-avatars/aviatorstyle"]},"inventory":[],"blocked":["0x9a3dc4f2d17cc2d45a81bd6c6459f48120d0e588"],"snapshots":{"face":"https://interconnected.online/content/contents/QmdTakLH8HW3K66Q7NGwwxQYkmVtAW2kNX36Py6LF3CcYy","body":"https://interconnected.online/content/contents/QmXapugu93eGFooktHqyzLFoTQ4s4HVYR1CzvTGqGCqSFx"},"hasConnectedWeb3":true}}```

**Comment by xpalaum** [comment]
Is this still happening? Shall it be labelled as "bug"?
Cannot prioritize based on current description.
