### ISSUE TITLE
Avatars should not be shown while teleporting out

### ISSUE THREAD

**Issue by moliva** [decentraland/explorer#58]
This is due to how we are reporting the position through our communication channels on kernel side.

We should send our new position eagerly to show the surrounding players that the player is no longer sharing their space.

**Comment by eordano** [comment]
@xpalaum can you verify this and close the issue if it's done?

**Comment by xpalaum** [comment]
This worked well, almost instantly.
Duplicate of explorer#28? Closing that one too.
