### ISSUE TITLE
fix: object interactions showing toaster when too far to interact

### ISSUE THREAD

**Issue by xpalaum** [decentraland/explorer#654]
When walking to a smart object, the interactions toaster appears before I can interact. I need to walk a couple more steps forward.

Steps:
1. Go to any scene with smart objects (for example -57,138 Serenity Island)
2. Get close to an smart object, but the farthest possible while the controls toaster still shows
3. Click and notice the smart object is not getting the input
4. Take a small step forward and now it works...

When fixing please check that it works well with 1st and 3rd person camera.

![image.png](https://images.zenhubusercontent.com/5d91dca0703cca0001efbe30/d7c409d5-e4c3-48bb-9718-363595550c4f)

**Comment by BrianAmadori** [comment]
Moved to unclear because we need the repro steps

**Comment by nearnshaw** [comment]
I think this issue is fixed now, isn't it?
@pravusjif

**Comment by marcosnc** [comment]
Please re-open this issue if needed.
