### ISSUE TITLE
materials don't look the same on Cubes vs Planes

### ISSUE THREAD

**Issue by nearnshaw** [decentraland/explorer#681]
If I add the same material to a cube or to a plane, they don't look the same. The plane looks a lot more whitewashed than the cube.

![image.png](https://images.zenhubusercontent.com/5d9b940e491c060001c8647b/61af7deb-a9e1-4ebf-8188-f1f22900a829)

This example scene shows this very clearly. I use two different materials: one a texture, and another a plane color w transparency... in all cases, the plane looks paler

[https://app.zenhub.com/files/220994476/f9038b3f-f968-4519-b368-f83170f14ec1/download](https://app.zenhub.com/files/220994476/f9038b3f-f968-4519-b368-f83170f14ec1/download)

**Comment by BrianAmadori** [comment]
This still happens? @nearnshaw

**Comment by nearnshaw** [comment]
@BrianAmadori   yep, still happens
you can easily check by running the attached scene on this ticket and setting the SDK version to next
I just checked that and the issue is still there

**Comment by BrianAmadori** [comment]
@nearnshaw this issue was fixed by the PlaneShape normals PR.
