### ISSUE TITLE
DLS: configure and test Daily Rewards campaign

### ISSUE THREAD

**Issue by xpalaum** [decentraland/explorer#687]
Here we configure the campaign, assign the NFTs, and do a team test round to make sure we are providing a good experience and catch any issues before release.

1pgr: https://docs.google.com/document/d/16gBeK1v5wrNBIs2Imagxh1SwjQzpRqolgQ5VQQEhVS4
NFT spreadsheet: https://docs.google.com/spreadsheets/u/1/d/1xwQWiEluWIVtGpaDEHX6A-AJbpzmc3Fr2tFdwOZVk0w/edit

**Comment by BrianAmadori** [comment]
Closing stale issue. I figure we will create new issues related to this when this feature is re-introduced.
