### ISSUE TITLE
NPS: avoid showing survey during tutorial

### ISSUE THREAD

**Issue by xpalaum** [decentraland/explorer#689]
![image.png](https://images.zenhubusercontent.com/5d91dca0703cca0001efbe30/b2e63a91-c3f4-4e0c-820f-8dfd46f047d0)

**Comment by BrianAmadori** [comment]
@xpalaum I think this is already done. It was covered by this PR: https://github.com/decentraland/explorer/pull/678

**Comment by xpalaum** [comment]
Oh, I had agreed with frami and Boris to add the issue to the next sprint. No problem, but unfortunately, after revieweing the code, it is not what I was expecting :S

Expected: 
Keep triggering the survey from setLoadingScreenVisible(), but add the condition that tutorial has to be finished. Basically avoid showing the survey on the loading screen within the tutorial, and instead show it on a subsequent loading screen after the tutorial is well over.

Current:
The survey is now out of loading screen and into the end of the tutorial which is not ideal.

Unless I'm missing something let's change it one more time, this time for good.

@BrianAmadori @2fd @moliva

**Comment by eordano** [comment]
Covered by: NPS disabled.
