### ISSUE TITLE
[Severe] Starting a new scene on the SDK shows the minimap

### ISSUE THREAD

**Issue by eordano** [decentraland/explorer#712]
We should hide it!

![image](https://user-images.githubusercontent.com/42750/76135661-de5e9700-6007-11ea-8e46-73d756d73706.png)

**Comment by nearnshaw** [comment]
I don't consider this a bug really,
I'd leave it on purpose 


I use it a lot to know what way the scene is facing relative to the map
Plus you get a little bit of context about how it will fit into the world,  eg: on what side there's a road

**Comment by BrianAmadori** [comment]
We are closing this bug. Please re-open if a new action is required.
