### ISSUE TITLE
Errors loading scenes (error while resolving new scenes around)

### ISSUE THREAD

**Issue by xpalaum** [decentraland/explorer#714]
I spawned at Genesis Plaza, walked towards -9,10 and then took the road to 1,10.

- Notice many 404 / missing Asset Bundle errors.
- Once I reached 1,10 some scenes permanently failed to load.

![image.png](https://images.zenhubusercontent.com/5d91dca0703cca0001efbe30/e21d7a60-ff9d-49ba-89e3-7c772b8d1e32)

**Comment by BrianAmadori** [comment]
I think the error that made the scenes stop loading is the last one "error while resolving new scenes around" as the asset bundle errors are inoffensive.
