### ISSUE TITLE
Loading screen - Messages style

### ISSUE THREAD

**Issue by RominaMarchetti** [decentraland/explorer#73]
![image.png](https://images.zenhubusercontent.com/5d91f7e9df37660001a11578/69cd81bd-ad6d-49fc-84f7-6660c28a00c1)

Fonts here: [https://app.zenhub.com/files/154520831/f3ed824a-2911-41d4-8ca8-fd844d2fe74d/download](https://app.zenhub.com/files/154520831/f3ed824a-2911-41d4-8ca8-fd844d2fe74d/download)

Tips: San Francisco Heavy
Loading status: San Francisco Semi-Bold

**Comment by marcosnc** [comment]
Loading Screen was re-implemented.
