### ISSUE TITLE
Some textures look worse in 6.4.7

### ISSUE THREAD

**Issue by nearnshaw** [decentraland/explorer#742]
A user reported that textures in his models used to look a lot better in 6.4.4 vs the current SDK version (6.4.7)

They used to look just like in his editing tools, but now they look "blotchy".

![image.png](https://images.zenhubusercontent.com/5d9b940e491c060001c8647b/5f9df71c-e54a-461c-8165-d641cc6876bc)

[https://app.zenhub.com/files/220994476/72ce19d1-c6b9-4b15-b8f8-84215d8119a7/download](https://app.zenhub.com/files/220994476/72ce19d1-c6b9-4b15-b8f8-84215d8119a7/download)

Did we maybe just change the default texture resolution in preview?

**Comment by nearnshaw** [comment]
could this be related to this comment by @dzsunyec?

it seems setting the texture filtering mode to 0:NEAREST still doesn't show up after deployment

**Comment by dzsunyec** [comment]
I am also experiencing the blotchiness/banding issue in 6.4.7 (see SDK preview comparison image below), but I'm assuming it has to do with texture bit depth and probably separate issue from the filtering. 

Setting the filtering mode to NEAREST works with both the SDK Materials and Blender exported materials **in preview**, but not working in the deployed scene with neither 6.4.4 or 6.4.7.

![texture_banding](https://user-images.githubusercontent.com/3963713/80274605-ef5c8800-86db-11ea-9a60-4720fca0c6b7.png)

**Comment by BrianAmadori** [comment]
We think this issue is related to texture compression. We are going to check if there are better compression alternatives but removing compression is not an option for now.

**Comment by BrianAmadori** [comment]
Just saw that we are using `Compress(false)` (low quality) on `GLTFSceneImporter`. Maybe this is related to that code.

**Comment by AjimenezDCL** [comment]
HQ Compression: ![textures_compression_hq](https://user-images.githubusercontent.com/50231608/96886945-5c32be00-1484-11eb-9a51-523212267a03.png)
Normal Compression: ![textures_compression_normal](https://user-images.githubusercontent.com/50231608/96886949-5ccb5480-1484-11eb-8076-b93e8cb6af66.png)
No Compression: ![textures_no_compression](https://user-images.githubusercontent.com/50231608/96886952-5d63eb00-1484-11eb-9120-82fcc4927e4b.png)

I just tested with different settings for compresion and it's not helping that much. So we are closing the ticket as a not-an-issue. Sadly removing compression is not an option currently.

**Comment by bricevdm** [comment]
> I just tested with different settings for compresion and it's not helping that much. So we are closing the ticket as a not-an-issue. Sadly removing compression is not an option currently.

@AjimenezDCL  It's not an issue in this specific case (an albedo texture), but it makes other types of maps close to unusable, especially emission maps and normals, both of which need proper bit-depth to work properly. There's a choice made between bit-depth and file size since compression is applied on all inputs right? We can't use a texture lookup of 32px with smooth gradients, it would show banding anyway, even if it's only a few Kb and the size is not an issue.
