### ISSUE TITLE
Scenes with ethereum controller no longer working

### ISSUE THREAD

**Issue by nearnshaw** [decentraland/explorer#765]
Scenes that use the Ethereum Controller not working in preview, using the @next version of the SDK

For example:

https://github.com/decentraland-scenes/MANA-Burning-Altar

[https://app.zenhub.com/files/220994476/1ba89c04-4690-4a9c-9198-cae7d106b799/download](https://app.zenhub.com/files/220994476/1ba89c04-4690-4a9c-9198-cae7d106b799/download)

![Screen Shot 2020-03-25 at 09.12.57.png](https://images.zenhubusercontent.com/5d9b940e491c060001c8647b/7bfe1643-29c9-4260-9ba4-d5d3983e663b)

**Comment by moliva** [comment]
This issue was in fact triggered by:
- [#752](https://github.com/decentraland/explorer/issues/752): Not being able to trigger transactions by clicking on objects
- Lack of feedback when using `EthereumController#requirePayment` method with a non-supported coin (e.g. MANA)
