### ISSUE TITLE
Scene textures stutter when loading

### ISSUE THREAD

**Issue by nearnshaw** [decentraland/explorer#785]
Several scenes have their textures stuttering to invisible while they load, when they finish loading sometimes they end up with part of the model invisible.

![image.png](https://images.zenhubusercontent.com/5d9b940e491c060001c8647b/0030546a-a6f2-4c4d-8659-21a78c9bcc11)

See here, for example, where models don't finish loading well
https://play.decentraland.org/?position=-83%2C64

If you load this scene at these coordinates directly, the stuttering might happen while you're seeing the black screen, but to see it you can spawn about 10 parcels away and then walk towards here, and you'll see the scene loading with the stuttering effect.  Or move around the vegas district and you'll see most buildings are affected.

Discussing this w Brian, he says that probably the material from the green blockers is being accidentally applied to these models, that's why it stutters.

I sometimes also experience this effect in preview when doing a hot reload after editing the scene's code

**Comment by pravusjif** [comment]
It's easier to reproduce the issue by starting in a pos like -71,72 and walking towards -76,69. At -76,69 there are 2 small buildings  that ALWAYS have this issue.
