### ISSUE TITLE
On-hover text doesn't work from all angles on all entitites

### ISSUE THREAD

**Issue by nearnshaw** [decentraland/explorer#794]
For some entities, the on-hover text when pointing the curser doesn't always work.

Take this one for example:

[https://app.zenhub.com/files/220994476/738b53f7-f299-437a-8474-851c2f1fd147/download](https://app.zenhub.com/files/220994476/738b53f7-f299-437a-8474-851c2f1fd147/download)

Its collider looks like this:
![image.png](https://images.zenhubusercontent.com/5d9b940e491c060001c8647b/68763414-3a05-42c8-b1c9-fbaf2f4ea1b3)

But try adding it to a scene w the following code:

```ts

let guestBook = new Entity()
guestBook.addComponent(
  new Transform({
    position: new Vector3(8, 0, 8),
  })
)
guestBook.addComponent(new GLTFShape('models/Guestbook_book.glb'))
guestBook.addComponent(
  new OnPointerDown(
    () => {
      log('OPENED GUESTBOOK')
    },
    { hoverText: 'Open' }
  )
)
engine.addEntity(guestBook)
```

You'll see that the "open" text appears in UI when looking at the book from certain angles, but not when looking at it from others.
Weird.
Shibu went over various iterations of this object trying to get it to work better, without any luck

**Comment by pravusjif** [comment]
I just confirmed the problem with this, it's not a bug. The model pivot is wrong (and thus the position used to check the distance is not at the book you are seeing).

You can easily check that by positioning it in the scene.
