### ISSUE TITLE
Friends HUD integration

### ISSUE THREAD

**Issue by BrianAmadori** [decentraland/explorer#837]
This includes:

- [x] Integrate basic friends HUD UI, friend list + whisper button + friend request list 
- [x] Wire UI to HUDController
- [x] Integrate UI to taskbar
- [x] Wire UI to kernel events (request accepted/denied, populate friends list, etc)
- [x] Wire whisper button to chat (whisper button should add a `/w friend` automatically upon press)
- [x] Integrate UI final art
- [ ] "Add new friend" feature (resolve how to track username errors, etc.)

Romi checklist: 

**Friends**

- [x] Empty state of both lists (friends & requests)
- [x] Divide Friends List into Online / Offline friends
- [x] Divide Add Friends List into Received / Sent
- [x] Request notification badge
- [x] After player A accepts player B request, show toast "now you and X are friends"
- [x] After player A declines player B request, show confirmation modal.
- [x] After  clicking cancel friend request (sent or received), show confirmation modal.
- [x] Add friend or cancel request from Player card
- [x] Hotkey -> Press L key to open and close (also  Esc) Friends List.
- [ ] Scrollbar reference
- [x] CTA on players' row: message, menu (when hover), accept / decline friends request, cancel friend  request sent.
- [ ] Search  friend Toast Messages: failed / succeed  

**Chat widget**

- [ ] New Message notification badge

Figma
https://www.figma.com/file/A12sJmYNNie4bhlI9rex3e/DCL-UI-UX-2.0?node-id=114%3A780

Technical 1pgr
https://docs.google.com/document/d/1Bt0qbub9V80z-9XcNFAJk3ribc8wvsV0sOZiNB9XfAI/edit#

Product  1pgr
https://docs.google.com/document/d/1Bt0qbub9V80z-9XcNFAJk3ribc8wvsV0sOZiNB9XfAI/edit#heading=h.5mfkzbi366hl

**Comment by RominaMarchetti** [comment]
- [ ] - Divide Friends List into Online / Offline friends
- [ ] - Scrollbar reference
- [ ] - Empty state of both lists (friends & requests)
- [ ] - Hotkey -> Press L key to open and close (also  Esc) Friends List.
- [ ] - Request notification badge
- [ ] - Decline/accept Friend Request from Add Friends Tab
- [ ] - After player A accepts player B request, show toast "now you and X are friends"
- [ ] - After player A declines player B request, show confirmation modal.
- [ ] - Cancel friend request from player card and Friends widget
- [ ] - When  hover a player's row menu button appears to open friends  options.
- [ ] - Search  friend Toast Messages: failed / succeed
- [ ]
