### ISSUE TITLE
GLTF->AB: Add test coverage

### ISSUE THREAD

**Issue by eordano** [decentraland/explorer#9]

**Comment by pravusjif** [comment]
I created branch `asset-promise-assetbundle-placeholder-tests` with every set of AssetPromise_GLTF tests for AssetBundles (copy-pasted and renamed accordingly every test).

Started experimenting with AssetBundle instantiation during tests in `Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/Tests/AssetBundle/AnyAssetPromiseShould.cs` -> `BeSetupCorrectlyAfterLoad()` but couldn't get the instantiation to work.
My guess is there is a problem with the 'contentProvider' that's being created for the tests (although the GLTF tests work with the same content provider...)

For testing that, you should have a `/Users/pravus/GIT/explorer/unity-client/TestResources/AssetBundles/`with an AssetBundle there. You can ping me or Brian to get an assetbundle for testing.
