### ISSUE TITLE
Other avatar sometimes not visible in Mini-Map

### ISSUE THREAD

**Issue by xpalaum** [decentraland/explorer#95]
Tested in .zone
While we (Alex and Xavi) were testing the bug reported as explorer#94, we also observed that several times we were not seeing each other in the mini-map. This was random but happened 2-3 times out of ~6 times.

**Comment by xpalaum** [comment]
Confirmed it happens as of Dec-27 and just testing with 3-4 people

**Comment by nearnshaw** [comment]
does this still happen?  
I haven't experienced it lately, might be already solved
